# Site settings
title: NIME2025 - Supplementary Demos
tag_text: NIME2025
description: This page contains supplementary material for the NIME2025 paper "Repurposing a Rhythm Accompaniment System for Pipe Organ Performance"
# baseurl: "/blog" # the subpath of your site, e.g. /blog
# url: "https://example.com" # the base hostname & protocol for your site, e.g. http://example.com

plugins:
  - jekyll-seo-tag

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed
